services:
  keycloak-db:
    image: postgres:13-alpine
    container_name: keycloak-db
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - keycloak-net
    expose:
      - 5432
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    depends_on:
    - keycloak-db
    networks:
      - keycloak-net
    ports:
      - "8080:8080"
    volumes:
      - ./certs/fullchain.pem:/etc/x509/https/tls.crt
      - ./certs/privkey.pem:/etc/x509/https/tls.key
    environment:
      KC_DB:       postgres
      KC_DB_URL:   jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key


networks:
  keycloak-net:

volumes:
  keycloak-datastore: