services:
    kong-db:
      image: postgres:13-alpine
      container_name: kong-db
      networks:
        - kong-net
      volumes:
        - kong-datastore:/var/lib/postgresql/data
      environment:
        - "POSTGRES_USER=kong"
        - "POSTGRES_DB=kong_gw"
        - "POSTGRES_PASSWORD=kongpass"
      expose:
        - 5432

    kong-migrations:
      image: kong:2.8.3
      container_name: kong-migrations
      depends_on:
        - kong-db
      command: kong migrations bootstrap --vv
      environment:
        KONG_DATABASE: postgres
        KONG_PG_HOST: kong-db
        KONG_PG_PORT: 5432
        KONG_PG_DATABASE: kong_gw
        KONG_PG_USER: kong
        KONG_PG_PASSWORD: kongpass
      networks:
        - kong-net

    kong-gateway:
        image: local/kong:2.8-oidc
        build:
          dockerfile: ./Dockerfile
        container_name: kong-gateway
        depends_on:
          - kong-db
        environment:
          KONG_DATABASE: postgres
          KONG_PG_HOST: kong-db
          KONG_PG_PORT: 5432
          KONG_PG_DATABASE: kong_gw
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kongpass
          KONG_PROXY_ACCESS_LOG: /dev/stdout
          KONG_ADMIN_ACCESS_LOG: /dev/stdout
          KONG_PROXY_ERROR_LOG: /dev/stderr
          KONG_ADMIN_ERROR_LOG: /dev/stderr
          KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
          KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
          KONG_PLUGINS: bundled,oidc
        ports:
          - 8000:8000
          - 8443:8443
          - 8001:8001
          - 8444:8444
        networks:
          - kong-net

    keycloak-db:
      image: postgres:13-alpine
      container_name: keycloak-db
      volumes: 
        - keycloak-datastore:/var/lib/postgresql/data
      networks:
        - keycloak-net
      expose:
        - 5432
      environment:
        POSTGRES_DB:       keycloak
        POSTGRES_USER:     keycloak
        POSTGRES_PASSWORD: keycloak

    keycloak:
      image: keycloak/keycloak:26.0
      container_name: keycloak
      command: start-dev
      depends_on:
      - keycloak-db
      networks:
        - keycloak-net
      ports:
        - "8080:8080"
      environment:
        KC_DB:       postgres
        KC_DB_URL:   jdbc:postgresql://keycloak-db/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak
        KEYCLOAK_ADMIN:           admin
        KEYCLOAK_ADMIN_PASSWORD:  admin

    konga-db:
      image: postgres:13-alpine
      container_name: konga-db
      networks:
        - kong-net
      volumes:
        - konga-datastore:/var/lib/postgresql/data
      environment:
        - "POSTGRES_USER=konga"
        - "POSTGRES_DB=konga"
        - "POSTGRES_PASSWORD=konga"
      expose:
        - 5432

    konga:
      image: pantsel/konga:0.14.9
      ports:
        - 1337:1337
      links:
        - kong-gateway:kong-gateway
      container_name: konga
      environment:
        DB_ADAPTER: postgres
        DB_HOST: konga-db
        DB_PORT: '5432'
        DB_USER: konga
        DB_PASSWORD: konga
        DB_DATABASE: konga
        NODE_ENV: development
      networks:
        - kong-net


networks:
  kong-net:
  keycloak-net:

volumes:
  kong-datastore:
  keycloak-datastore:
  konga-datastore: